---
#
# Tasks to uninstall wildfly server
#

- name: Check "{{wf.user_home}}" exists
  stat:
    path: "{{ wf.user_home }}"
  register: wf_user_home_status

- name: Remove wildfly user, files, directories
  block:
    - name: Check wildfly system spec file
      stat:
        path: "/etc/systemd/system/{{ wf.service }}.service"
      register: wf_service_status

    - name: Stop wildfly server
      systemd:
        name: "{{ wf.service }}"
        state: stopped
      when:
        - wf_service_status.stat.exists

    - name: Remove wildfly system spec
      file:
        path: "{{ item }}"
        state: absent
        force: yes
      with_items:
        - "/etc/systemd/system/{{ wf.service }}.service"
        - "{{ wf.conf_dir }}"
        - "{{ wf.user_home }}"

    - name: Delete wildfly user
      user:
        name: "{{ wf.user }}"
        state: absent
  when:
    - wf_user_home_status.stat.exists

