---
# tasks file for sample_app
#

- name: Create workspace directory for sample application
  file:
    path: '{{ sample_app.workspace_dir }}'
    state: directory
    recurse: yes
    owner: '{{ sample_app.owner }}'
    group: '{{ sample_app.group }}'

- name: Clone project
  git:
    repo: '{{ sample_app.repo }}'
    dest: '{{ sample_app.workspace_dir }}'
    accept_hostkey: yes
    clone: yes

- name: Set ownership on sample application directory
  file:
    path: '{{ sample_app.workspace_dir }}'
    owner: '{{ sample_app.owner }}'
    group: '{{ sample_app.group }}'
    recurse: yes

- name: Build project
  shell: |
    mvn wildfly:deploy
  args:
    executable: /bin/bash
    chdir: '{{ sample_app.workspace_dir }}'
  register: mvn_output

- name: Print build output
  debug: var=mvn_output
