---
# test
- name: test
  hosts: all 
  vars_files:
    - vars/main.yml

  tasks:

    - name: Check Application URL
      uri:
        url: "http://{{ ansible_fqdn }}:{{ wf.app_port }}/{{ sample_app.app_uri }}"
        status_code: 200
      tags:
        - never
        - test