---
#
# Playbook to install Wildfly server
#

- name: Playbook to install Wildfly server
  hosts: all
  become: true
  vars_files:
    - vars/main.yml

  roles:
    - role: teardown_wildfly
      tags:
        - never
        - uninstall
