---
#
# Tasks to configure Wildfly server (Initial configuration)
#

- name: Create {{wf.conf_dir}} directory
  file:
    path: "{{ wf.conf_dir }}"
    state: directory
    recurse: yes

- name: Copy wildfly configuration file
  copy:
    src: "{{ wf.user_home }}/docs/contrib/scripts/systemd/wildfly.conf"
    dest: "{{ wf.conf_dir }}/"
    remote_src: yes

- name: Copy wildfly launch script
  copy:
    src: "{{ wf.user_home }}/docs/contrib/scripts/systemd/launch.sh"
    dest: "{{ wf.user_home }}/bin"
    remote_src: yes
    mode: 0755

- name: Set ownership of all files in {{wf.user_home}} to wildfly user
  file:
    path: "{{wf.user_home}}"
    state: directory
    owner: "{{wf.user}}"
    group: "{{wf.group}}"
    recurse: yes
  notify:
    - start_wildfly

- name: Set execute permissions on all script files in {{wf.user_home}}/bin directory
  file:
    path: "{{ item }}"
    owner: "{{wf.user}}"
    group: "{{wf.group}}"
    mode: 0755
  with_fileglob: "{{ wf.user_home }}/bin/*.sh"

- name: Copy system spec file
  copy:
    src: "{{ wf.user_home }}/docs/contrib/scripts/systemd/wildfly.service"
    dest: "/etc/systemd/system/"
    remote_src: yes

- name: Include Task to setup Firewall rules
  include_tasks: setup_fw_rules.yml

