---
#
# Tasks to start/stop wildfly service
#

- name: Start Wildfly service
  systemd:
    name: wildfly
    daemon_reload: yes
    enabled: yes
    state: started
  tags:
    - start

- name: Stop Wildfly service
  systemd:
    name: wildfly
    daemon_reload: yes
    enabled: yes
    state: stopped
  tags:
    - stop
